# Generated by Django 5.2.15 on 2026-06-26 22:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_loginlog_success_alter_loginlog_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='twofactorcode',
            name='admin_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='twofactorcode',
            name='admin_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='twofactorcode',
            name='admin_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_two_factor_codes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='twofactorcode',
            name='attempted_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='twofactorcode',
            name='attempted_username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='twofactorcode',
            name='entered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
