# Generated by Django 5.2.15 on 2026-06-26 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_twofactorcode_admin_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='twofactorcode',
            name='entered_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
